### ISSUE TITLE
StartProcess 失败

### ISSUE THREAD

**Issue by ltaoo** [qtgolang/SunnyNet#12]
大佬请教个问题，这段代码

```golang
ok := Sunny.StartProcess()
		if !ok {
			fmt.Println("ERROR 启动进程代理失败")
			fmt.Println("按 Ctrl+C 退出...")
			select {}
		}
```

有些用户会到 `!ok` 分支中，但是不知道原因。而且反馈说几天前正常，今天就一直到 `!ok`，而且说在别人电脑又是正常的。

能否 `StartProcess` 返回具体的错误原因？

**Comment by qtgolang** [comment]
请确保具有管理员权限，应该就可以了，并且确保不是精简版Windows 系统，例如Ghost系统，精简版系统可能会有问题暂时无解

**Comment by ltaoo** [comment]
> 请确保具有管理员权限，应该就可以了，并且确保不是精简版Windows 系统，例如Ghost系统，精简版系统可能会有问题暂时无解

好的，感谢，应该是系统问题。
