### ISSUE TITLE
【websocket】mac上,不能主动发送

### ISSUE THREAD

**Issue by shenjo** [qtgolang/SunnyNet#2]
<img width="635" alt="image" src="https://github.com/qtgolang/SunnyNet/assets/13912646/e54f795d-b617-4fb3-be40-5623a9237d8c">

1. 没有发送相关的选项以及发送按钮
2. 不能输入，显示只读不可编辑

**Comment by qtgolang** [comment]
你应该到：https://github.com/qtgolang/SunnyNetTools/issues 这里提问，不过我发现的确有这个问题，下个版本将修复

**Comment by shenjo** [comment]
好的，谢谢。
